//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gunluk.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class gun
    {
        public int id { get; set; }
        public string tarih { get; set; }
        public string gunlukMesajı { get; set; }
        public string bilgi { get; set; }
        public string tecrübe { get; set; }
    }
}
